all: generate print input count

generate:
	gcc table.c generate.c -o generate
print:
	gcc table.c print.c -o print
input:
	gcc table.c input.c -o input
count:
	gcc table.c count.c -o count
clean:
	rm print generate input count