[tool.poetry]
name = "advance"
version = "0.1.0"
description = ""
authors = ["KiRiLLBEL <kirillbelonosov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
